# Generated by Django 3.2.8 on 2021-11-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=50)),
                ('project_desc', models.CharField(max_length=50)),
                ('project_img', models.FileField(default=None, max_length=250, null=True, upload_to='projects/')),
                ('project_link', models.CharField(max_length=100)),
            ],
        ),
    ]
